apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: boardmaria
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: boardmaria
  source:
    repoURL: https://github.com/xaviergold/BoardMaria_ArgoCD.git
    targetRevision: main
    path: charts/boardmaria
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
